---
- name: Instalar dependencias base
  hosts: local
  become: true
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes
        cache_valid_time: 3600  #no actualice si fue hace menos de una hora

    - name: Instalar paquetes esenciales
      apt:
        name:
          - git
          - curl
          - nginx
          - certbot
          - python3-certbot-nginx
        name: present
